/** NEXUS AI — Quiet Machine Cinema contact page: composed outreach through glass surfaces, execution rails, and transparent static-form behavior. */
import { AtSign, MessageSquareText, Send, Waypoints } from "lucide-react";
import { type FormEvent } from "react";
import { toast } from "sonner";
import { ProductFrame, RailList, RouteAction, SectionLead } from "@/components/MarketingPrimitives";

export default function Contact() {
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    toast.info("Contact delivery is not connected yet. Your message has not been sent.", { description: "Connect an official contact endpoint to activate this form." });
  };

  return <ProductFrame scene="contact" title="Contact" description="Start a product, partnership, or documentation conversation with NEXUS AI." eyebrow="CONTACT / OPEN CONTEXT" hero={<>Bring the signal.<br /><em>We’ll make room.</em></>} detail="Use this page to prepare a clear conversation about NEXUS AI. Describe the work, the context, and the outcome you are exploring; delivery activates when an official contact route is connected." actions={<><RouteAction href="#inquiry">Write an inquiry</RouteAction><RouteAction href="/docs" secondary>Read documentation</RouteAction></>} aside={<div className="route-console"><div className="terminal-head"><span>CONTACT ROUTE</span><span className="status-live"><i /> OPEN CONTEXT</span></div><div className="p-6 font-mono text-xs leading-7 text-white/60">01&nbsp;&nbsp;INTENT<br /><span className="text-[#8AE8FF]">↓</span><br />02&nbsp;&nbsp;CONTEXT<br /><span className="text-[#8AE8FF]">↓</span><br />03&nbsp;&nbsp;INQUIRY<br /><span className="text-[#8AE8FF]">↓</span><br />04&nbsp;&nbsp;REPLY PATH</div></div>}>
    <section className="section-shell border-t border-white/10" id="inquiry"><div className="grid gap-12 lg:grid-cols-[.76fr_1.24fr] lg:gap-20"><SectionLead eyebrow="01 — START A CONVERSATION" title={<>Give the team<br /><em>the right context.</em></>} detail="A useful inquiry starts with what you are trying to move forward. The form is ready for product, documentation, partnership, or general questions without suggesting an unconfigured delivery channel." /><form className="route-console p-5 sm:p-7" onSubmit={handleSubmit}><div className="terminal-head -mx-5 -mt-5 mb-7 sm:-mx-7 sm:-mt-7"><span>INQUIRY DRAFT</span><span className="result-tag">NOT SENT</span></div><div className="grid gap-5 sm:grid-cols-2"><label className="contact-field"><span>Name</span><input name="name" autoComplete="name" required placeholder="Your name" /></label><label className="contact-field"><span>Email</span><input name="email" type="email" autoComplete="email" required placeholder="you@company.com" /></label></div><div className="mt-5 grid gap-5 sm:grid-cols-2"><label className="contact-field"><span>Organization <small>optional</small></span><input name="organization" autoComplete="organization" placeholder="Company or team" /></label><label className="contact-field"><span>Topic</span><select name="topic" required defaultValue=""><option value="" disabled>Choose a topic</option><option value="product">Product inquiry</option><option value="docs">Documentation</option><option value="partnership">Partnership</option><option value="other">General question</option></select></label></div><label className="contact-field mt-5 block"><span>Message</span><textarea name="message" required rows={6} placeholder="What are you trying to make possible with NEXUS AI?" /></label><div className="mt-6 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><p className="max-w-md text-xs leading-5 text-white/43">This static form does not transmit your message until an official contact endpoint is connected.</p><button className="solid-button !px-6 !py-3.5" type="submit">Prepare inquiry <Send className="h-4 w-4" /></button></div></form></div></section>
    <section className="section-shell feature-story-beat border-t border-white/10"><div className="grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:gap-20"><RailList items={[{ title: "Product conversations", detail: "Bring the task, workflow, or environment you are evaluating so the conversation has a practical starting point.", icon: MessageSquareText, state: "CONTEXT" }, { title: "Documentation questions", detail: "Point to the guide, configuration path, or technical boundary that needs clearer support.", icon: AtSign, state: "REFERENCE" }, { title: "Partnership pathways", detail: "Describe the audience, integration context, or product direction you want to explore.", icon: Waypoints, state: "DIRECTION" }]} /><SectionLead eyebrow="02 — WHAT HELPS" title={<>Clear intent.<br /><em>Useful next steps.</em></>} detail="Contact should feel like the rest of the product: an observable route with enough context to make the next response intentional." /></div></section>
    <section className="section-shell border-t border-white/10"><div className="grid gap-12 lg:grid-cols-[.82fr_1.18fr] lg:gap-20"><SectionLead eyebrow="03 — BEFORE YOU SEND" title={<>The product map<br /><em>may have the answer.</em></>} detail="For installation, CLI, security, or release questions, the relevant product route may provide the clearest current context while the official contact channel is being prepared." /><div className="flex flex-col items-start gap-3 sm:flex-row sm:items-center"><RouteAction href="/docs">Browse documentation</RouteAction><RouteAction href="/download" secondary>View download path</RouteAction></div></div></section>
  </ProductFrame>;
}
