/** NEXUS AI — Quiet Machine Cinema features page: capability storytelling through execution rails rather than generic feature grids. */
import { Activity, Braces, CheckCheck, FileText, FolderOpen, ShieldCheck, Terminal, Wrench } from "lucide-react";
import { ProductFrame, RailList, RouteAction, SectionLead, SoftCard } from "@/components/MarketingPrimitives";

export default function Features() {
  return <ProductFrame scene="features" title="Features" description="Explore the observable, multi-step capabilities of NEXUS AI." eyebrow="FEATURES / OBSERVABLE WORK" hero={<>Don’t just ask AI.<br /><em>Give it a job.</em></>} detail="NEXUS AI helps move a goal through a deliberate sequence: understand the task, plan the work, use the right tools, surface risk, and return with verification." actions={<><RouteAction href="/download">Download NEXUS</RouteAction><RouteAction href="/cli" secondary>Explore CLI</RouteAction></>} aside={<div className="route-console"><div className="terminal-head"><span>EXECUTION MODEL</span><span className="status-live"><i /> OBSERVABLE</span></div><RailList items={[{ title: "Intent", detail: "Task received", state: "01" }, { title: "Plan", detail: "Steps prepared", state: "02" }, { title: "Work", detail: "Tools coordinated", state: "03" }, { title: "Verify", detail: "Outcome checked", state: "04" }]} /></div>}>
    <section className="section-shell border-t border-white/10"><div className="grid gap-12 lg:grid-cols-[.75fr_1.25fr] lg:gap-20"><SectionLead eyebrow="01 — AUTONOMOUS EXECUTION" title={<>A plan that<br /><em>keeps moving.</em></>} detail="NEXUS AI is designed for work that has more than one step — where context, decisions, tools, and a final check belong in one visible run." /><RailList items={[{ title: "Intelligent planning", detail: "Break a complex objective into a clear sequence before acting.", icon: Activity }, { title: "Persistent context", detail: "Keep the relevant task details connected across the workflow.", icon: FileText }, { title: "Multi-step workflows", detail: "Carry the work from request through execution and verification.", icon: CheckCheck }]} /></div></section>
    <section className="section-shell feature-story-beat border-t border-white/10"><div className="mx-auto max-w-5xl text-center"><p className="eyebrow mb-6">02 — EXECUTION EXAMPLE</p><h2 className="display-title text-5xl leading-[.92] tracking-[-.06em] sm:text-7xl md:text-8xl">“Analyze this project.”<br /><em>Then show the work.</em></h2><div className="mt-12 text-left"><RailList items={[{ title: "Project understanding", detail: "Build context from the visible code, files, and structure in the working environment.", icon: FolderOpen, state: "TRACE" }, { title: "Tool usage", detail: "Coordinate file, terminal, and configured tool actions as the plan calls for them.", icon: Wrench, state: "TRACE" }, { title: "Human approval", detail: "Surface consequential work before execution continues.", icon: ShieldCheck, state: "GATE" }, { title: "Verification", detail: "Compare the returned work against the task objective.", icon: CheckCheck, state: "RESULT" }]} /></div></div></section>
    <section className="section-shell border-t border-white/10"><div className="grid gap-12 lg:grid-cols-[1.1fr_.9fr] lg:gap-20"><div className="grid gap-3 sm:grid-cols-2"><SoftCard title="File interaction" detail="Work with files available in the active environment as part of a visible task plan." icon={FolderOpen} /><SoftCard title="Terminal interaction" detail="Use the command line only where the work calls for it and its role is observable." icon={Terminal} /><SoftCard title="API interaction" detail="Connect to configured tools and services when an API is part of the workflow." icon={Braces} /><SoftCard title="Risk detection" detail="Bring attention to potentially consequential actions before the task continues." icon={ShieldCheck} /></div><SectionLead eyebrow="03 — TOOLS WITH CONTEXT" title={<>The right tool.<br /><em>The visible reason.</em></>} detail="Capabilities work together in a single execution narrative rather than as isolated features." /></div></section>
  </ProductFrame>;
}
