/** NEXUS AI — Quiet Machine Cinema home: concise cinematic introduction that directs detailed journeys to dedicated product routes. */
import { Activity, ArrowDown, Eye, ShieldCheck, Wrench } from "lucide-react";
import { Brand, PageMeta, SiteFooter, SiteNav } from "@/components/SiteChrome";
import { CopyCommandButton, RailList, RouteAction, SectionLead, SoftCard } from "@/components/MarketingPrimitives";
import { CreatorSection } from "@/components/CreatorSection";


const videoSource = "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260314_131748_f2ca2a28-fed7-44c8-b9a9-bd9acdd5ec31.mp4";

export default function Home() {
  return <PageMeta title="Your AI Agent. On Your Machine." description="NEXUS AI is an autonomous AI agent product for observable work on your machine."><main className="overflow-x-hidden bg-[#031B29] text-white" id="top">
    <section className="relative flex min-h-[100svh] flex-col overflow-hidden border-b border-white/10"><video className="absolute inset-0 z-0 h-full w-full object-cover" autoPlay loop muted playsInline aria-hidden="true"><source src={videoSource} type="video/mp4" /></video><div className="home-video-wash" aria-hidden="true" /><SiteNav /><div className="relative z-10 mx-auto flex w-full max-w-7xl flex-1 items-center px-5 pb-24 pt-16 sm:px-8 sm:pb-28 sm:pt-24"><div className="max-w-5xl"><div className="hero-identity animate-fade-rise"><Brand /><span className="hero-identity-rule" /><span className="hero-identity-meta">LOCAL AGENT / 01</span></div><p className="eyebrow animate-fade-rise mb-7">AUTONOMOUS AGENT · LOCAL ENVIRONMENT</p><h1 className="display-title animate-fade-rise text-5xl leading-[.92] tracking-[-.06em] text-white sm:text-7xl md:text-[6.65rem] lg:text-[8.1rem]">NEXUS AI,<br /><em>Ready When You Are.</em></h1><p className="animate-fade-rise-delay mt-8 max-w-2xl text-base leading-7 text-white/72 sm:mt-9 sm:text-lg sm:leading-8">Give NEXUS AI an outcome, then follow the plan, tools, approvals, and result as work moves through your environment.</p><div className="animate-fade-rise-delay-2 mt-9 flex flex-col items-start gap-3 sm:mt-12 sm:flex-row"><RouteAction href="/download">Download NEXUS</RouteAction><RouteAction href="/features" secondary>Explore features</RouteAction></div><p className="animate-fade-rise-delay-2 mt-8 text-xs tracking-[.16em] text-white/58">LOCAL DEVICE · CLI · OBSERVABLE EXECUTION</p></div></div><a href="#what-is-nexus" className="absolute bottom-7 left-1/2 z-10 flex -translate-x-1/2 flex-col items-center gap-2 text-[.62rem] tracking-[.2em] text-white/60 transition hover:text-white">SCROLL <ArrowDown className="h-4 w-4" /></a></section>

    <section id="what-is-nexus" className="section-shell border-t border-white/10"><div className="grid gap-12 lg:grid-cols-[.76fr_1.24fr] lg:gap-20"><SectionLead eyebrow="01 — WHAT IS NEXUS AI" title={<>A task can be<br /><em>more than a prompt.</em></>} detail="NEXUS AI is a product vision for autonomous, multi-step work that stays close to your machine and visible to you." /><RailList items={[{ title: "Give it a goal", detail: "Start with the outcome, not a scattered list of tool instructions.", icon: Activity }, { title: "Inspect the approach", detail: "Follow the plan as it organizes context and determines the next move.", icon: Eye }, { title: "Direct the work", detail: "Stay present at the approvals and decisions that call for your judgment.", icon: ShieldCheck }]} /></div></section>

    <section className="section-shell feature-story-beat border-t border-white/10"><div className="grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:gap-20"><div className="order-2 grid gap-3 sm:grid-cols-2 lg:order-1"><SoftCard title="Autonomous execution" detail="Carry an objective across multiple visible steps." icon={Activity} /><SoftCard title="Planning & verification" detail="Prepare the work, then compare the outcome to the goal." icon={Eye} /><SoftCard title="Tool coordination" detail="Bring files, terminals, and configured tools into one task path." icon={Wrench} /><SoftCard title="Human approval" detail="Keep consequential decisions in view when they matter." icon={ShieldCheck} /></div><div className="order-1 lg:order-2"><SectionLead eyebrow="02 — CAPABILITIES" title={<>Work that<br /><em>shows its shape.</em></>} detail="The full capabilities story lives on its own page, with examples organized around the execution trace rather than a generic feature grid." /><div className="mt-9"><RouteAction href="/features" secondary>Explore features</RouteAction></div></div></div></section>

    <section className="section-shell border-t border-white/10"><div className="grid gap-12 lg:grid-cols-[.84fr_1.16fr] lg:gap-20"><SectionLead eyebrow="03 — SHORT WORKFLOW" title={<>Intent becomes<br /><em>observable work.</em></>} detail="NEXUS AI is shaped around an execution path that is straightforward to follow from task to result." /><div className="route-console"><div className="terminal-head"><span>EXECUTION TRACE</span><span className="status-live"><i /> ACTIVE</span></div><RailList items={[{ title: "Task", detail: "The desired outcome enters the workspace.", state: "01" }, { title: "Plan", detail: "NEXUS AI prepares a visible sequence.", state: "02" }, { title: "Execution", detail: "Tools and actions move through the requested work.", state: "03" }, { title: "Verification", detail: "The result returns with its trace.", state: "04" }]} /></div></div></section>

    <section className="section-shell border-t border-white/10"><div className="grid gap-12 lg:grid-cols-[1.08fr_.92fr] lg:gap-20"><div className="route-console order-2 lg:order-1"><div className="terminal-head"><span>LOCAL CONTEXT</span><span className="status-live"><i /> YOUR MACHINE</span></div><div className="p-7"><p className="font-mono text-sm leading-7 text-white/72">workspace / selected<br />tools / configured<br />permissions / reviewed</p><div className="mt-8 border-t border-white/10 pt-5 text-sm leading-6 text-white/47">The detailed installation, system requirements, platform releases, and first-run path are organized in the download hub.</div></div></div><div className="order-1 lg:order-2"><SectionLead eyebrow="04 — ON YOUR MACHINE" title={<>Close to the<br /><em>context that matters.</em></>} detail="NEXUS AI is positioned around the device, project, workspace, and tools you already use." /><div className="mt-9"><RouteAction href="/download" secondary>View download hub</RouteAction></div></div></div></section>

    <section className="section-shell border-t border-white/10"><div className="grid gap-12 lg:grid-cols-[.72fr_1.28fr] lg:gap-20"><SectionLead eyebrow="05 — NEXUS CLI" title={<>The terminal is<br /><em>first-class.</em></>} detail="Install NEXUS AI directly from your terminal. Run tasks, inspect execution, handle approvals, and manage workflows." /><div className="route-console"><div className="terminal-head"><span>NEXUS CLI</span><span className="status-live"><i /> TERMINAL</span></div><div className="p-7 space-y-4 font-mono text-sm leading-7 text-white/80"><div><p className="text-xs text-white/40 mb-1"># INSTALL NEXUS AI</p><div className="flex items-center justify-between gap-3 text-white"><span className="text-[#8AE8FF]">$</span><span className="break-all font-semibold">npm install -g @nexus-ai-nexoralabs/cli</span><CopyCommandButton command="npm install -g @nexus-ai-nexoralabs/cli" /></div></div><div><p className="text-xs text-white/40 mb-1"># STARTUP</p><p className="text-white"><span className="text-[#8AE8FF]">$</span> nexus</p></div><div className="pt-2 border-t border-white/10 mt-4"><RouteAction href="/cli" secondary>Explore CLI</RouteAction></div></div></div></div></section>

    <section className="section-shell border-t border-white/10"><div className="grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:gap-20"><div className="grid gap-3 sm:grid-cols-2"><SoftCard title="Permissions" detail="Keep the requested access context visible." icon={ShieldCheck} /><SoftCard title="Risk awareness" detail="Surface consequential actions for attention." icon={Eye} /><SoftCard title="Approvals" detail="Pause where a human decision should guide the work." icon={ShieldCheck} /><SoftCard title="Activity trace" detail="Follow progress through planning, execution, and verification." icon={Activity} /></div><div><SectionLead eyebrow="06 — SECURITY" title={<>Control is part<br /><em>of the workflow.</em></>} detail="The security page explains the task-to-verification model with careful language that avoids unsupported claims." /><div className="mt-9"><RouteAction href="/security" secondary>Explore security</RouteAction></div></div></div></section>

    <CreatorSection />

    <section className="border-t border-white/10 px-5 py-24 sm:px-8 sm:py-32"><div className="final-execution mx-auto max-w-7xl border-y border-white/16 py-14 text-center sm:py-20"><div className="mx-auto mb-8 w-max"><Brand /></div><p className="eyebrow mb-6">NEXUS AI / READY FOR THE NEXT TASK</p><h2 className="display-title text-5xl leading-[.92] tracking-[-.06em] text-white sm:text-7xl md:text-8xl">Give the work<br /><em>a direction.</em></h2><p className="mx-auto mt-7 max-w-md text-base leading-7 text-white/58">Discover the product, prepare your machine, and give NEXUS AI an outcome to carry forward.</p><div className="mt-10 flex flex-col items-center justify-center gap-3 sm:flex-row"><RouteAction href="/download">Download NEXUS</RouteAction><RouteAction href="/docs" secondary>Read documentation</RouteAction></div><div className="completion-trace" aria-hidden="true"><span /><i /><i /><i /><span /></div></div></section>

    <SiteFooter />
  </main></PageMeta>;
}
