/** NEXUS AI — Quiet Machine Cinema releases page: an honest, prepared empty state for a future verified release source. */
import { Archive, FileCheck2, RefreshCw } from "lucide-react";
import { ProductFrame, RailList, RouteAction, SectionLead } from "@/components/MarketingPrimitives";

export default function Releases() {
  return <ProductFrame scene="releases" title="Releases" description="Follow official NEXUS AI releases when verified release information is available." eyebrow="RELEASES / VERIFIED SOURCE" hero={<>The next release<br /><em>starts with the source.</em></>} detail="NEXUS AI release information belongs to an official release feed. Versions, dates, notes, archives, and downloads remain intentionally absent until that source is connected." actions={<><RouteAction href="/download">Download hub</RouteAction><RouteAction href="/docs" secondary>Read documentation</RouteAction></>} aside={<div className="route-console"><div className="terminal-head"><span>RELEASE FEED</span><span className="result-tag">NOT CONNECTED</span></div><div className="p-7"><p className="text-sm leading-6 text-white/61">No verified release feed is available in this project.</p><div className="mt-8 flex items-center gap-3 text-xs tracking-[.12em] text-white/36"><span className="signal-node opacity-40" /> WAITING FOR OFFICIAL DATA</div></div></div>}>
    <section className="section-shell border-t border-white/10"><div className="grid gap-12 lg:grid-cols-[.78fr_1.22fr] lg:gap-20"><SectionLead eyebrow="LATEST RELEASE" title={<>Nothing invented.<br /><em>Everything ready.</em></>} detail="When official data is available, this page will display only the fields supported by that source." /><RailList items={[{ title: "Latest version", detail: "Awaiting verified release data.", icon: RefreshCw, state: "SOURCE-GATED" }, { title: "Release date", detail: "Awaiting verified release data.", icon: FileCheck2, state: "SOURCE-GATED" }, { title: "What’s new", detail: "Awaiting verified release notes.", icon: Archive, state: "SOURCE-GATED" }, { title: "Previous releases", detail: "Awaiting verified release archive.", icon: Archive, state: "SOURCE-GATED" }]} /></div></section>
    <section className="section-shell feature-story-beat border-t border-white/10"><div className="mx-auto max-w-4xl text-center"><p className="eyebrow mb-6">RELEASE INTEGRITY</p><h2 className="display-title text-5xl leading-[.92] tracking-[-.06em] sm:text-7xl">Don’t guess at<br /><em>what people install.</em></h2><p className="mx-auto mt-7 max-w-2xl text-base leading-7 text-white/57">Downloads, package names, checksums, architecture support, and release notes must come from the published release source. This UI is ready to show them when that source exists.</p></div></section>
  </ProductFrame>;
}
