/** NEXUS AI — Quiet Machine Cinema security page: careful workflow language without unsupported security or privacy claims. */
import { Activity, CheckCheck, Eye, FolderLock, ShieldCheck, TriangleAlert, UserCheck } from "lucide-react";
import { ProductFrame, RailList, RouteAction, SectionLead, SoftCard } from "@/components/MarketingPrimitives";

export default function Security() {
  return <ProductFrame scene="security" title="Security" description="Understand how NEXUS AI makes task execution, permissions, risk, and approvals more visible." eyebrow="SECURITY / HUMAN CONTROL" hero={<>Visible work.<br /><em>Deliberate control.</em></>} detail="NEXUS AI is designed to keep execution legible: a task becomes a plan, risk and permissions are considered, and human approval can appear before consequential work continues." actions={<><RouteAction href="/download">Download NEXUS</RouteAction><RouteAction href="/docs" secondary>Read documentation</RouteAction></>} aside={<div className="route-console"><div className="terminal-head"><span>WORKFLOW STATUS</span><span className="status-live"><i /> HUMAN GATE</span></div><div className="p-6 font-mono text-xs leading-7 text-white/60">TASK<br /><span className="text-[#8AE8FF]">↓</span> PLAN<br /><span className="text-[#8AE8FF]">↓</span> RISK ANALYSIS<br /><span className="text-[#8AE8FF]">↓</span> PERMISSION CHECK<br /><span className="text-[#8AE8FF]">↓</span> APPROVAL IF REQUIRED<br /><span className="text-[#8AE8FF]">↓</span> EXECUTION<br /><span className="text-[#8AE8FF]">↓</span> VERIFICATION</div></div>}>
    <section className="section-shell border-t border-white/10"><div className="grid gap-12 lg:grid-cols-[.78fr_1.22fr] lg:gap-20"><SectionLead eyebrow="01 — EXECUTION FLOW" title={<>A task should<br /><em>show its path.</em></>} detail="The workflow is presented as an execution model, not a claim about any particular technical implementation or security certification." /><RailList items={[{ title: "Task", detail: "An outcome starts the work.", icon: Activity }, { title: "Planning", detail: "NEXUS AI prepares the intended sequence.", icon: Eye }, { title: "Risk analysis", detail: "Potentially consequential actions can be surfaced for attention.", icon: TriangleAlert }, { title: "Permission check", detail: "The relevant access and workspace context can be reviewed.", icon: FolderLock }, { title: "Approval if required", detail: "Human confirmation can gate work before it proceeds.", icon: UserCheck }, { title: "Execution & verification", detail: "Work continues with progress and a final outcome trace.", icon: CheckCheck }]} /></div></section>
    <section className="section-shell feature-story-beat border-t border-white/10"><div className="grid gap-12 lg:grid-cols-[1.15fr_.85fr] lg:gap-20"><div className="route-console"><div className="terminal-head"><span>APPROVAL STATE</span><span className="status-live"><i /> WAITING</span></div><div className="p-7"><p className="font-mono text-sm leading-7 text-white/76">Action requires human approval before execution can continue.</p><div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="route-card"><span className="workflow-index">REQUEST</span><h3>Execution context</h3><p>Review the task, scope, and action request before choosing how to continue.</p></div><div className="route-card"><span className="workflow-index">DECISION</span><h3>Control stays present</h3><p>Approve, reject, or inspect the plan according to the product’s documented controls.</p></div></div></div></div><SectionLead eyebrow="02 — APPROVALS" title={<>Pause when<br /><em>the work matters.</em></>} detail="The security story focuses on decision points, visibility, and the human role — without representing unsupported guarantees." /></div></section>
    <section className="section-shell border-t border-white/10"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><SoftCard title="Permissions" detail="Review the access context that a task requests before moving forward." icon={ShieldCheck} /><SoftCard title="Risk levels" detail="Use task context to bring attention to actions that need more scrutiny." icon={TriangleAlert} /><SoftCard title="Execution visibility" detail="Follow the plan, tools, progress, and outcome through a visible trace." icon={Eye} /><SoftCard title="Activity history" detail="Keep the execution narrative available where the product implements it." icon={Activity} /><SoftCard title="Workspace access" detail="Set the relevant project or working context before the task proceeds." icon={FolderLock} /></div></section>
  </ProductFrame>;
}
