import { DocsLayout } from "@/components/DocsLayout";
import { FolderOpen, Globe, Shield } from "lucide-react";


export default function Workspaces() {
  return (
    <DocsLayout
      title="Workspaces"
      description="Learn about NEXUS AI workspace scoping, file organization, directory isolation, inspection, and web previewing."
      currentId="workspaces"
    >
      {/* HEADER SECTION */}
      <div className="mb-10 pb-8 border-b border-white/10">
        <p className="eyebrow mb-2">DOCUMENTATION · 08</p>
        <h1 className="display-title text-4xl sm:text-5xl font-normal text-white mb-4">
          NEXUS <em>Workspaces</em>
        </h1>
        <p className="text-base sm:text-lg text-white/65 leading-relaxed max-w-3xl">
          The NEXUS AI workspace is the configured directory boundary that anchors agent file operations, project outputs, and local web previews.
        </p>
      </div>

      {/* WORKSPACE ROOT */}
      <section className="mb-14">
        <h2 className="text-2xl font-semibold text-white mb-4">Workspace Root</h2>
        <p className="text-white/70 leading-7 mb-4">
          When you launch <code className="text-[#8AE8FF]">nexus</code>, the CLI automatically binds to your active terminal directory as the workspace root. You can also specify an explicit directory target using the <code className="text-[#8AE8FF]">--workspace</code> flag:
        </p>

        <div className="soft-panel rounded-xl p-5 border border-white/14 bg-[#010b12] font-mono text-sm my-4">
          <p className="text-white mb-2">
            <span className="text-[#8AE8FF]">$</span> nexus --workspace C:\Projects\my-web-app
          </p>
        </div>
      </section>

      {/* FILES CREATED BY NEXUS */}
      <section className="mb-14">
        <h2 className="text-2xl font-semibold text-white mb-4">Project File Organization</h2>
        <p className="text-white/70 leading-7 mb-4">
          All files generated by NEXUS AI agents are saved directly inside your workspace directory, organized by project folders:
        </p>

        <div className="soft-panel rounded-xl p-5 border border-white/14 bg-[#010b12] font-mono text-xs text-white/80 space-y-1 my-4">
          <p className="text-[#8AE8FF] font-semibold">NEXUS-Workspace/</p>
          <p>├── calculator/</p>
          <p>│   ├── index.html</p>
          <p>│   ├── style.css</p>
          <p>│   └── script.js</p>
          <p>│</p>
          <p>├── landing-page/</p>
          <p>│   ├── index.html</p>
          <p>│   ├── style.css</p>
          <p>│   └── script.js</p>
        </div>
      </section>

      {/* INSPECTING & PREVIEWING */}
      <section className="mb-14">
        <h2 className="text-2xl font-semibold text-white mb-4">Inspecting &amp; Previewing Workspaces</h2>
        <div className="grid gap-4 sm:grid-cols-2 my-4">
          <div className="soft-panel rounded-xl p-5 border border-white/10">
            <h3 className="text-sm font-semibold text-[#8AE8FF] mb-2 flex items-center gap-2">
              <FolderOpen className="h-4 w-4" /> Inspecting with `/workspace`
            </h3>
            <p className="text-xs text-white/65 leading-5 mb-3">
              Type <code className="text-white font-mono">/workspace</code> in an active CLI session to view your current root path, file count, and directory status.
            </p>
          </div>

          <div className="soft-panel rounded-xl p-5 border border-white/10">
            <h3 className="text-sm font-semibold text-[#8AE8FF] mb-2 flex items-center gap-2">
              <Globe className="h-4 w-4" /> Previewing with `/preview`
            </h3>
            <p className="text-xs text-white/65 leading-5 mb-3">
              Type <code className="text-white font-mono">/preview</code> after generating a web project to launch a local HTTP preview server at <code className="text-white">http://localhost:3000/</code>.
            </p>
          </div>
        </div>
      </section>

      {/* WORKSPACE SECURITY & TROUBLESHOOTING */}
      <section className="mb-8">
        <h2 className="text-2xl font-semibold text-white mb-4 flex items-center gap-2">
          <Shield className="h-5 w-5 text-[#8AE8FF]" /> Workspace Security &amp; Path Troubleshooting
        </h2>
        <div className="space-y-4 text-xs font-mono text-white/80">
          <div className="soft-panel rounded-xl p-4 border border-white/10">
            <p className="text-[#8AE8FF] font-semibold mb-1">PATH_TRAVERSAL_DENIED</p>
            <p className="text-white/60 font-sans">Occurs if a prompt attempts to write outside the workspace tree. Solution: Ensure target paths are relative to your current project folder.</p>
          </div>

          <div className="soft-panel rounded-xl p-4 border border-white/10">
            <p className="text-[#8AE8FF] font-semibold mb-1">Directory Not Found</p>
            <p className="text-white/60 font-sans">Occurs if the `--workspace` parameter targets a non-existent folder. Solution: Create the directory before passing the flag.</p>
          </div>
        </div>
      </section>
    </DocsLayout>
  );
}
